version: "3"

services:
  node:
    image: node:16
    container_name: xp_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db 
      MYSQL_DB: XPCorretora
      PORT: '3000'
      JWT_SECRET: meuSegredo

  db:
    container_name: xp_api_db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3308:3306

